### ISSUE TITLE
TypeError: getHydrationScript is not a function

### ISSUE THREAD

**Issue by GaZaTu** [solidjs/solid#1186]
### Describe the bug

Running the following script during SSG/SSR produces `TypeError: getHydrationScript is not a function` since 1.5.x.
```typescript
const { renderToStringAsync, getHydrationScript } = await import("solid-js/web")
```
It used to work in 1.4.x with `generateHydrationScript`.

Maybe someone has an idea.

### Your Example Website or App

https://github.com/GaZaTu/gazatu-website-graphql-solidjs-spectre/tree/7437895779aef7c799ad2aa42617adf64c84d91e

### Steps to Reproduce the Bug or Issue

1. `npm install`
2. `npm run build:ssg`

### Expected behavior

no error fdm

### Platform

- OS: Windows
- Version: 1.5.1

**Comment by ryansolid** [comment]
I think you pointed it out. It should be `generateHydrationScript` not `getHydrationScript`. I messed up something on the types sorry about that. I will fix it. In the meanwhile use `generateHydrationScript`.
