### ISSUE TITLE
Potential breaking changes in 1.7.10

### ISSUE THREAD

**Issue by phungleson** [solidjs/solid#1848]
### Describe the bug

When I updated to 1.7.10 and ran some tests and I got this error.

```
TypeError: fn is not a function
 ❯ untrack ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:486:33
    484| }
    485| function untrack(fn) {
    486|   if (Listener === null) return fn();
       |                                 ^
    487|   const listener = Listener;
    488|   Listener = null;
 ❯ runTop ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:844:24
 ❯ runUserEffects ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:973:36
 ❯ ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:929:34
 ❯ runUpdates ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:877:17
 ❯ completeUpdates ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:929:17
 ❯ runUpdates ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:878:5
 ❯ createRoot ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/dist/dev.js:193:12
 ❯ render ../../node_modules/.pnpm/solid-js@1.7.10/node_modules/solid-js/web/dist/dev.js:556:3
 ❯ Module.render ../../node_modules/.pnpm/@solidjs+testing-library@0.8.4_@solidjs+router@0.8.3_solid-js@1.7.10/node_modules/@solidjs/testing-library/dist/index.js:64:65
```

I checked my code and all `untrack` is calling with `() => {}`.

I reverted back to `1.7.9` and tests passed again.

Maybe there are issues with other libraries (i.e. testing library), let me know if you need more information, happy to look into this, thanks!

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

N/A

### Platform

- OS: macOS
- Version:
    "@solidjs/router": "^0.8.3",
    "@solidjs/testing-library": "^0.8.4",
    "vite": "4.4.9",
    "vite-plugin-solid": "^2.7.0",
    "vitest": "^0.34.1",

**Comment by timothyallan** [comment]
I'm getting this exact error as well with the update. The stack trace is massive, and looks like a lot of entries are from Felte: https://felte.dev/docs/solid/getting-started 
![Screenshot 2023-08-09 at 9 16 31 PM](https://github.com/solidjs/solid/assets/1995135/5a0b2291-ac99-4d11-8639-b3f85183eaa8)
