### ISSUE TITLE
[Solid 2.0 Beta.6] svg with dynamic attribute or text fails within a <Show>

### ISSUE THREAD

**Issue by echab** [solidjs/solid#2674]
### Describe the bug

Within an `<svg>`, if the children of `<Show>`  contain some svg elements with dynamic attributes or text, an error is thrown (it works with solid 1.9.12).

### Your Example Website or App

https://stackblitz.com/edit/solidjs-templates-jrzmgmvh?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Click on "Open Preview in new Tab" to see the error in the F12 console.

2. Clicking on the button, the counter block at 2, with the following error (for attribute setting):
```
chunk-LY7APLER.js?v=c121a6f8:1126 Uncaught StatusError: node.setAttribute is not a function
    at notifyStatus (chunk-LY7APLER.js?v=c121a6f8:1126:13)
    at recompute (chunk-LY7APLER.js?v=c121a6f8:1310:5)
    at runHeap (chunk-LY7APLER.js?v=c121a6f8:125:41)
    at _GlobalQueue.flush (chunk-LY7APLER.js?v=c121a6f8:375:7)
    at flush (chunk-LY7APLER.js?v=c121a6f8:585:17)
Caused by: TypeError: node.setAttribute is not a function
    at setAttribute (@solidjs_web.js?v=f189e41d:544:13)
    at Object._effectFn (App.tsx:27:57)
    at Object.runEffect (chunk-LY7APLER.js?v=c121a6f8:1898:27)
    at effect (chunk-LY7APLER.js?v=c121a6f8:1883:118)
    at createRenderEffect (chunk-LY7APLER.js?v=c121a6f8:2038:3)
    at createRenderEffect2 (chunk-LY7APLER.js?v=c121a6f8:4093:83)
    at effect (@solidjs_web.js?v=f189e41d:438:41)
    at get children (App.tsx:26:34)
    at Show.createMemo.name [as _fn] (chunk-LY7APLER.js?v=c121a6f8:4312:27)
    at recompute (chunk-LY7APLER.js?v=c121a6f8:1293:32)
```

3. comment out the third `<Show>` to test the last case with text setting:
```
chunk-LY7APLER.js?v=c121a6f8:1126 Uncaught StatusError: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.
    at notifyStatus (chunk-LY7APLER.js?v=c121a6f8:1126:13)
    at recompute (chunk-LY7APLER.js?v=c121a6f8:1310:5)
    at runHeap (chunk-LY7APLER.js?v=c121a6f8:125:41)
    at _GlobalQueue.flush (chunk-LY7APLER.js?v=c121a6f8:375:7)
    at flush (chunk-LY7APLER.js?v=c121a6f8:585:17)
Caused by: HierarchyRequestError: Failed to execute 'insertBefore' on 'Node': This node type does not support this method.
    at insert (@solidjs_web.js?v=f189e41d:668:12)
    at get children (App.tsx:31:34)
    at Show.createMemo.name [as _fn] (chunk-LY7APLER.js?v=c121a6f8:4312:27)
    at recompute (chunk-LY7APLER.js?v=c121a6f8:1293:32)
    at runHeap (chunk-LY7APLER.js?v=c121a6f8:125:41)
    at _GlobalQueue.flush (chunk-LY7APLER.js?v=c121a6f8:375:7)
    at flush (chunk-LY7APLER.js?v=c121a6f8:585:17)
```

### Expected behavior

I expect to have no error using solid2.0, with no need to wrap each dynamic elements within additional `<svg>`.

### Platform

- OS: Windows, stackblitz
- Browser: Chrome
- Version: solidjs 2.0.0-beta.6

**Comment by titoBouzout** [comment]
Thanks, this is a regression introduced 3 days ago, PR is up at https://github.com/ryansolid/dom-expressions/pull/504

**Comment by ryansolid** [comment]
And it is merged. Will be in beta.7 when released.
